# Прогнозирование (out-of-sample)

Рассмотрим модель регрессии

$$
	(\log) y=\beta_0+\beta_1 (\log)x_1+\cdots+\beta_k (\log) x_k+u
$$

В матричной записи

\begin{align*}
	(\log)y&=x^\top\beta+u & \beta&=\begin{pmatrix} \beta_0 \\ \beta_1 \\ \vdots \\ \beta_k \end{pmatrix} &
	x &=\begin{pmatrix} 1 \\ (\log)x_1 \\ \vdots \\ (\log) x_k \end{pmatrix}
\end{align*}

Пусть $\hat{\beta}$ – оценки коэффициентов (результат подгонки модели на обучающей выборке)

Прогноз по подогнанной (обученной модели) на новом наборе данных (регрессорах)

$$
	\hat{y}=(\exp) x^\top \hat{\beta}
$$

In [15]:
import numpy as np
import pandas as pd

from statsmodels.formula.api import ols

# Не показывать FutureWarnings
import warnings
warnings.simplefilter(action='ignore', category=Warning)

In [16]:
# импорт данных
df = pd.read_csv('sleep75.csv')

## Спецификация и подгонка

In [9]:
# спецификация модели через формулу
mod = ols(formula='sleep~1 + totwrk +age+smsa', data=df)
# подгонка модели
res = mod.fit()

In [4]:
# параметры подогнанной модели регрессии с округлением
res.params.round(2)

Intercept    3498.67
totwrk         -0.15
age             3.00
smsa          -73.50
dtype: float64

## Прогнозирование

In [5]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'totwrk': [2150, 1950, 2240], 'age': [37, 26, 28], 'smsa': [1, 0, 1] })
new_data

   totwrk  age  smsa
0    2150   37     1
1    1950   26     0
2    2240   28     1

In [6]:
# Прогноз
res.predict(exog=new_data, transform=True).round(2)

0    3212.70
1    3283.31
2    3172.18
dtype: float64

1 sleep equation #1
Для набора данных sleep75 рассмотрим линейную регрессию sleep на totwrk, age, south, male, smsa, yngkid, marr.

Результаты оценивания:

In [10]:
# спецификация модели через формулу
mod = ols(formula='sleep~1 + totwrk +age+south+male+smsa+yngkid+marr', data=df)
# подгонка модели
res = mod.fit()

In [11]:
# параметры подогнанной модели регрессии с округлением
res.params.round(2)

Intercept    3450.91
totwrk         -0.17
age             2.69
south         101.57
male           87.67
smsa          -54.75
yngkid        -13.96
marr           31.21
dtype: float64

In [21]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'totwrk': [2150, 1950, 2240], 'age': [37, 28, 26], 'south': [0, 1, 0], 'male': [1,1,0], 'smsa': [1, 0, 0], 'yngkid': [0,1,0], 'marr': [1,0,0] })
new_data

   totwrk  age  south  male  smsa  yngkid  marr
0    2150   37      0     1     1       0     1
1    1950   28      1     1     0       1     0
2    2240   26      0     0     0       0     0

In [22]:
# Прогноз
res.predict(exog=new_data, transform=True).round(2)

0    3250.68
1    3371.46
2    3141.73
dtype: float64

In [23]:
#2 спецификация модели через формулу
mod = ols(formula='sleep~1 + totwrk +age+I(age**2)+south+male', data=df)
# подгонка модели
res = mod.fit()

In [24]:
# параметры подогнанной модели регрессии с округлением
res.params.round(2)

Intercept      3613.99
totwrk           -0.17
age              -6.25
I(age ** 2)       0.11
south           114.55
male             90.46
dtype: float64

In [25]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'totwrk': [2160, 1720, 2390], 'age': [32, 24, 44], 'south': [1, 0, 0], 'male': [0,1,1] })
new_data

   totwrk  age  south  male
0    2160   32      1     0
1    1720   24      0     1
2    2390   44      0     1

In [26]:
# Прогноз
res.predict(exog=new_data, transform=True).round(2)

0    3278.46
1    3329.25
2    3240.11
dtype: float64

In [28]:
#3 импорт данных
df = pd.read_csv('wage2.csv')

In [31]:
# спецификация модели через формулу
mod = ols(formula='np.log(wage)~1 +age+ IQ +south+married+urban', data=df)
# подгонка модели
res = mod.fit()

In [32]:
# параметры подогнанной модели регрессии с округлением
res.params.round(2)

Intercept    4.97
age          0.02
IQ           0.01
south       -0.10
married      0.20
urban        0.17
dtype: float64

In [33]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'age': [36, 29, 25], 'IQ': [105, 123, 112], 'south': [1, 0, 1], 'married': [1,1,0], 'urban': [1, 0, 1] })
new_data

   age   IQ  south  married  urban
0   36  105      1        1      1
1   29  123      0        1      0
2   25  112      1        0      1

In [37]:
# Прогноз
np.exp(res.predict(exog=new_data, transform=True)).round(2)

0    969.95
1    897.93
2    665.07
dtype: float64

In [39]:
#4 импорт данных
df = pd.read_csv('wage1.csv')

In [40]:
# спецификация модели через формулу
mod = ols(formula='np.log(wage)~1 + exper+I(exper**2)+female+married+smsa', data=df)
# подгонка модели
res = mod.fit()

In [41]:
# параметры подогнанной модели регрессии с округлением
res.params.round(2)

Intercept        1.25
exper            0.04
I(exper ** 2)   -0.00
female          -0.36
married          0.14
smsa             0.27
dtype: float64

In [42]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'exper': [5, 26, 38], 'female': [1, 0, 1], 'married': [1, 0, 1], 'smsa': [1,1,0] })
new_data

   exper  female  married  smsa
0      5       1        1     1
1     26       0        0     1
2     38       1        1     0

In [43]:
# Прогноз
np.exp(res.predict(exog=new_data, transform=True)).round(2)

0    4.35
1    7.10
2    3.74
dtype: float64

In [46]:
#5 импорт данных
df = pd.read_csv('Labour.csv')

In [48]:
# спецификация модели через формулу
mod = ols(formula='np.log(output)~1+ np.log( capital)+np.log(labour)', data=df)
# подгонка модели
res = mod.fit()

In [49]:
# параметры подогнанной модели регрессии с округлением
res.params.round(2)

Intercept         -1.71
np.log(capital)    0.21
np.log(labour)     0.71
dtype: float64

In [50]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'capital': [2.970, 10.450    , 3.850    ], 'labour': [85, 60, 105] })
new_data

   capital  labour
0     2.97      85
1    10.45      60
2     3.85     105

In [51]:
# Прогноз
np.exp(res.predict(exog=new_data, transform=True)).round(2)

0    5.42
1    5.49
2    6.65
dtype: float64

In [52]:
# спецификация модели через формулу
mod = ols(formula='np.log(output)~1+ np.log( capital)+np.log(labour)+I(np.log(capital)**2)+I(np.log(labour)**2)', data=df)
# подгонка модели
res = mod.fit()

In [53]:
# параметры подогнанной модели регрессии с округлением
res.params.round(2)

Intercept                 -1.30
np.log(capital)            0.18
np.log(labour)             0.52
I(np.log(capital) ** 2)    0.02
I(np.log(labour) ** 2)     0.02
dtype: float64

In [54]:
# Создадим датафрейм с новыми данными регрессоров для прогноза
new_data = pd.DataFrame({'capital': [22.140   ,7.320     ,0.670], 'labour': [ 407,  197, 31] })
new_data

   capital  labour
0    22.14     407
1     7.32     197
2     0.67      31

In [55]:
# Прогноз
np.exp(res.predict(exog=new_data, transform=True)).round(2)

0    27.37
1    11.46
2     1.89
dtype: float64